disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - function_parameter_count
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - line_length
  - operator_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - fastlane

cyclomatic_complexity: 30

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
function_body_length:
  - 150 # warning
  - 180 # error
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 1400 # warning
  - 1500 # error
# or they can set both explicitly
file_length:
  warning: 1400
  error: 1500
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 60
    error: 100
  excluded: iPhone # excluded via string
large_tuple:
  - 4 # warning
  - 5 # error
identifier_name:
  min_length: # only min_length
    error: 8 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube)
